version: "3.9"

networks:
  app-network:
    driver: overlay

volumes:
  data-product-postgres-sql:

services:
  product-postgres-sql:
    image: postgres:alpine
    volumes:
      - data-product-postgres-sql:/var/lib/postgresql/data
    env_file:
      - ov-ims-product/.env.postgres
    ports:
      - "5433:5432"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == database
      restart_policy:
        condition: on-failure

  ov-ims-product:
    depends_on:
      - product-postgres-sql
    image: openjdk:21
    container_name: ov-ims-product
    env_file:
      - ov-ims-product/.env
      - ov-ims-product/.env.postgres
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname != database
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./ov-ims-product/target/ov-ims-product-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]