server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka-1:9092
    consumer:
      group-id: io.github.jotabrc
      client-id: inventory-1
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: ov-ims-inv
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  redis:
    host: redis-cache
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    io.lettuce.core: TRACE
    io.lettuce: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.servlet.DispatcherServlet: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.cache.interceptor: DEBUG

ov:
  ims:
    validation:
      pattern:
        name: "[\\p{L}\\p{M}\\.\\s'-]{4,255}"
        string: "^$|^[A-Za-z0-9.,;!-'?§¶(){}\\[\\]€$R$\\s\\p{M}\\p{L}]+$"
        uuid: "\\p{XDigit}{8}-\\p{XDigit}{4}-\\p{XDigit}{4}-\\p{XDigit}{12}"